- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- server/provider/blocks.go
- server/provider/blocks_test.go
- server/provider/networkProvider.go
- server/provider/scheduledMiniblocks.go
- server/provider/scheduledMiniblocks_test.go
- server/provider/transactions.go
- server/provider/transactions_test.go
- version/constants.go
Generally speaking, if a block `N` contains a **scheduled** miniblock with an invalid transaction `T`, this transaction will be added in the intrashard miniblock of type **InvalidBlock**, which is stored in the receipts unit - and provided by the Node API, as well.
Though, if, additionally, block `N` is the first shard block after an epoch change, the aforementioned miniblock (from receipts unit) isn't provided by the API (regarding this, further debugging is needed on Node's side).
**Issue (duplicated / misleading balance-changing operations)**
Rosetta sees the invalid transaction `T` in block `N` (in a **scheduled** miniblock) and acknowledges it's balance-changing operations (not knowing it is invalid). Then, Rosetta sees transaction `T` in block `N+1` once again, and it's current …
> Rewrite handling of scheduled miniblocks. Fix handling of invalid scheduled transactions

- README.md
- docker/ObserverDevnet.dockerfile
- docker/ObserverMainnet.dockerfile
- docker/Rosetta.dockerfile
- server/provider/constants.go
- server/provider/scheduledMiniblocks.go
- server/provider/scheduledMiniblocks_test.go
- version/constants.go
- Handle edge case: cross-shard scheduled miniblocks with `construction state = final`.
- Added an extra condition to ignore empty (and artificial) invalid miniblocks (does not affect flow)
- Adjust docker images to set `StartInEpoch = false`
- Update readme (e.g. on how to avoid Docker caching when building images)
> Edge case: cross-shard scheduled miniblocks with construction state = final.

- server/factory/controllers.go
- server/provider/errors.go
- server/provider/errors_test.go
- server/provider/networkProvider.go
- server/services/accountService.go
- server/services/accountService_test.go
- server/services/blockService.go
- server/services/blockService_test.go
- server/services/constructionService.go
- server/services/constructionServiceFee.go
- server/services/constructionServiceFee_test.go
- server/services/errors.go
- server/services/mempoolService.go
- server/services/mempoolService_test.go
- server/services/networkService.go
- server/services/networkService_test.go
- server/services/offline_services.go
- version/constants.go
- Propagate information about original errors (see `error.details.originalError`) in the context of `GET account/balance`.
- Error definitions have been refactored (added an `errFactory`).
- Some error codes have changed, but this should not be a major version at this point (wrt. semver guidelines) - since `v1.0.0` is not released yet.
- More tests will be added in https://github.com/ElrondNetwork/rosetta/pull/11.
> Define errFactory. Propagate error info (e.g. for GET account).

- server/provider/constants.go
- server/provider/networkProvider.go
- version/constants.go
- Handle (check) errors. Previously, the error returned by `simplifyBlockWithScheduledTransactions` wasn't checked. This resulted in the block not being "simplified", but still returned to the caller (bug). As a consequence, when the _tip_ of the chain was a block N with processed (previously scheduled) miniblocks, and the request to block N+1 failed (see below), then the "not-simplified" N would re-emit transactions previously emitted in N-1 (as scheduled).
- Example of failed GET `block/by-nonce` requests (node API): `err = key ... not found in BlockHeaders `
- In the context of scheduled transactions, make sure the `N+1` block is final, as well.
The error was detected when performing a slow-paced [import-db](https://docs.elrond.com/validators/import-db/#docsNav) operation on epochs …
> Hotfix on handling scheduled transactions

- cmd/rosetta/main.go
Example:
```
INFO [time] Starting Rosetta... middleware = v0.1.6 specification = v1.4.12 node = rc/2022-july
```
> Print version when starting

- checks/mainnet/mainnet-data-start-after-10120628.json
Optimize (with respect to running time) the checker configuration for mainnet.
Estimated time to run: ~ 2-4 hours.
> Optimize checker config for mainnet.

- server/provider/scheduledMiniblocks.go
- version/constants.go
Always perform `simplifyBlockWithScheduledTransactions()`.
Previously, this step was skipped for blocks that only contained `normal` miniblocks, which lead to an incorrect handling of invalid scheduled transactions (that may be originating in the previous block).
> Always perform simplifyBlockWithScheduledTransactions().

- cmd/rosetta/main.go
- docker/ObserverDevnet.dockerfile
- docker/ObserverMainnet.dockerfile
- version/constants.go
- Do not log the API calls summary anymore
- Increase the log level of the observer to `*:DEBUG` (this leads to ~5-6 GB of logs per week, on mainnet).
> Adjust logging

- checks/devnet/devnet-data-historical.json
- checks/mainnet/README.md
- checks/mainnet/mainnet-data-historical.json
- server/provider/nodeStatus.go
- server/provider/nodeStatus_test.go
- server/resources/accountQueryOptions.go
- version/constants.go
- Account for rollback-related edge cases while node is syncing (in conjunction with scheduled miniblocks).
- Adjust end conditions of `check:data`.
- Minor refactoring.
> Historical lookup - part 2

- server/provider/interface.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- version/constants.go
The cache should hold copies of the blocks, because the pointers returned by `GetBlockByNonce` suffer mutations downstream (e.g. due to `simplifyBlockWithScheduledTransactions`). Such mutations should not affect the cached data.
> Hotfix: hold block copies in the cache

- server/services/constants.go
- server/services/transactionEventsController.go
- server/services/transactionEventsController_test.go
- server/services/transactionsFeaturesDetector.go
- server/services/transactionsFeaturesDetector_test.go
- server/services/transactionsTransformer.go
- version/constants.go
For invalid transactions of type "move balance" (both at _source_ and at _destination_) that contain the error `invalid meta transaction`, compute used gas (and fee) using solely the data movement component (without the execution component).
Edge case has been discovered on devnet, _actual_ shard 0 (not _projected_ shard 0). The fix has been tested by running a `check:data` flow (see [rosetta-checks](https://github.com/ElrondNetwork/rosetta-checks)).
> Fix fee computation for edge case "meta transaction is invalid".

- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- server/factory/provider.go
- server/provider/constants.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- server/provider/nodeStatus.go
- server/provider/nodeStatus_test.go
- server/provider/urls.go
- server/resources/network.go
- version/constants.go
Previously, rosetta provided an estimation for `oldest_block_identifier` (relying on a CLI argument called `--num-historical-blocks`). Here, we remove the estimation logic, and provide a precise value, instead.
In order to provide a precise value for `oldest_block_identifier`, rely on:
- `oldest_kept_epoch` provided by `node/status` (metric recently added on Node API)
- `node/epoch-start` (route recently added on Node API)
PR on elrond-go that is used as a basis for the implementation: https://github.com/ElrondNetwork/elrond-go/pull/4505
> Provide a precise value for "oldest block identifier"

- go.mod
- go.sum
- server/provider/errors.go
- server/provider/nodeStatus.go
- server/provider/nodeStatus_test.go
- server/services/blockService_test.go
- server/services/mempoolService_test.go
- server/services/operations.go
- server/services/transactionMetadata.go
- server/services/transactionMetadata_test.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- version/constants.go
- Add [transaction metadata](https://www.rosetta-api.org/docs/models/Transaction.html): 
```
{
"timestamp":         ...,
"value":             ...,
"nonce":             ...,
"typeOnSource":      ...,
"typeOnDestination": ...,
"epoch":             ...,
"sender":            ...,
"receiver":          ...,
"sourceShard":       ...,
"destinationShard":  ...,
"miniblock":         ...,
"miniblockType":     ...,
...
}
```
- Add new operation types, to better differentiate operations: `FeeRefundAsSmartContractResult`, `DeveloperRewardsAsSmartContractResult`.
- Improve error handling for `network/status`, when `highestFinalNonce == 0` (node didn't start syncing).
> Add transaction metadata. Make some operation types more explicit.

- server/services/constructionService.go
- server/services/constructionService_test.go
Add support for constructing cross-shard transactions - handle `receiver` and `value` from the preprocess metadata, when they are present.
Related to: https://github.com/ElrondNetwork/rosetta-checks/pull/7
The construction API will be partly refactored in https://github.com/ElrondNetwork/rosetta/pull/51.
> Workaround (quick fix) to support construction of cross-shard transactions

- README.md
- server/factory/components/disabledExternalConnector.go
- server/factory/controllers.go
- server/factory/interface.go
- server/factory/provider.go
- server/provider/constants.go
- server/provider/errors.go
- server/provider/networkProvider.go
- server/services/networkProviderExtension_test.go
- server/services/offline_services.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- testscommon/addresses.go
- testscommon/networkProviderMock.go
- testscommon/observerFacadeMock.go
fixed some linter and grammar issues
> linter and grammar fixes

- server/services/common.go
- Use `interface{}` instead of `any` - since we use `go 1.17` on [rosetta-docker](https://github.com/ElrondNetwork/rosetta-docker).
> Use interface{} instead of "any" (go 1.17).

- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- server/factory/interface.go
- server/factory/provider.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- server/provider/nodeStatus.go
- server/provider/nodeStatus_test.go
- server/resources/network.go
- server/services/constants.go
- server/services/interface.go
- server/services/networkService.go
- server/services/networkService_test.go
- testscommon/networkProviderMock.go
- version/constants.go
- the CLI flag `--observer-pubkey` has been removed. Observer's public key (BLS) is now returned in `/network/status` (peers substructure).
- Observer's version isn't hardcoded anymore in `version/constants.go`. Instead, it's fetched from the Observer's API. Rosetta's `/network/options` and `/network/status` now return this version.
- peer connections statistics (counts) are now returned in `/network/status`.
> Get extra details from node/status and return them in Rosetta API

- server/services/networkService.go
- server/services/networkService_test.go
- version/constants.go
Return middleware version, as well, in the response of `/network/options`.
See: https://www.rosetta-api.org/docs/models/Version.html
Example:
```
{
"version": {
"rosetta_version": "v1.4.12",
"node_version": "v1.3.48-devnet-hf01-0-g67d0313/go1.17.6/linux-amd64/f9b031042e",
"middleware_version": "v0.3.1"
},
...
}
```
> Add middleware version in response of "/network/options".

- server/services/constants.go
- server/services/transactionEventsController.go
- server/services/transactionEventsController_test.go
- version/constants.go
Adjust fee handling for invalid / intrashard transactions of type `MoveBalance` (at both _source_ and _destination_).
> (Low-impact) handle "meta transaction is invalid: not enough gas"

- README.md
Fixed the `README.md` file to accommodate the migration to the new organization.
> Fix readme file after migration

- server/provider/scheduledMiniblocks.go
- server/provider/scheduledMiniblocks_test.go
- version/constants.go
Sometimes, an invalid transaction processed in a _scheduled_ miniblock might have its smart contract result (if any) saved in the _receipts unit_ of both blocks `N` and `N+1`. This PR ignores the duplicate entries in block `N`, as returned by the Node API.
This issue is non-problematic, but, if not fixed, would result into some reconciliation failiures, for accounts that craft more exotic transactions (not simple transfer ones).
> Handle edge case on scheduled invalid transactions, with SCR outcome

- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- server/factory/interface.go
- server/factory/provider.go
- server/provider/currenciesProvider.go
- server/provider/currenciesProvider_test.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- server/resources/resources.go
- server/services/interface.go
- testscommon/networkProviderMock.go
New CLI arg, `custom-currencies`. E.g.:
```
rosetta [...]
--custom-currencies=ROSETTA-3a2edf
--custom-currencies=ROSETTA-057ab4
```
Additional refactoring.
> Receive custom currencies as CLI arg. Refactor, define a "CurrenciesProvider"

- server/services/constructionServiceFee_test.go
- server/services/converters.go
- server/services/converters_test.go
Add a few converters, to be used for creating (and parsing) ESDT transfers - in a following PR.
> Add converters - to be used in ESDT transfer construction (and parsing)

- server/factory/components/observerFacade.go
- server/factory/interface.go
- server/provider/interface.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- server/services/common.go
- server/services/common_test.go
- server/services/constants.go
- server/services/errors.go
- server/services/interface.go
- server/services/relayedTransactions.go
- server/services/relayedTransactions_test.go
- server/services/transactionEventsController.go
- server/services/transactionEventsController_test.go
- server/services/transactionFilters.go
- server/services/transactionsFeaturesDetector.go
- server/services/transactionsFeaturesDetector_test.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- testscommon/addresses.go
- testscommon/networkProviderMock.go
- testscommon/observerFacadeMock.go
- version/constants.go
While the balance changing operations are perfectly recoverable from most kinds of relayed transactions (given the smart contract results generated by the protocol), there is a case where this is only possible by also unwrapping and inspecting the _inner transaction_: when the relayed transaction is **completely intra-shard** (both the wrapping transaction and the inner transaction are intra-shard, in the same shard), and the processing of the transaction results into a **contract signal error**.
The PR handles this exotic case and emits an extra balance-changing operation.
> Handle intra-shard relayed transactions with signal error

- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- server/factory/provider.go
- server/provider/networkProvider.go
- server/provider/networkProvider_test.go
- server/services/blockService.go
- server/services/networkProviderExtension.go
- server/services/networkProviderExtension_test.go
- server/services/transactionsTransformer.go
- systemtests/proxyToObserverAdapter.go
- New CLI flag: `--handle-contracts` - whether to handle balance-changing operations for smart contracts, as well. By default, feature is disabled.
- Refactor `IsAddressObserved()`.
> New CLI flag: --handle-contracts. Minor refactoring.

- server/factory/interface.go
- server/provider/accounts.go
- server/provider/accounts_test.go
- server/provider/errors.go
- server/provider/tokenIdentifierParts.go
- server/provider/tokenIdentifierParts_test.go
- server/provider/urls.go
- server/provider/urls_test.go
- server/resources/accounts.go
- server/resources/resources.go
- server/services/accountService.go
- server/services/accountService_test.go
- server/services/interface.go
- server/services/networkProviderExtension.go
- server/services/networkProviderExtension_test.go
- server/services/transactionEvents.go
- server/services/transactionEventsController.go
- server/services/transactionEvents_test.go
- server/services/transactionsTransformer.go
- testscommon/networkProviderMock.go
- `NetworkProvider.GetAccountBalance()` -  a single method for getting balances (whether for the native currency or for custom ones).
- Handle non-fungible tokens in `GetAccountBalance()`, as well.
- Additional minor refactoring, plus unit tests
- System tests for NFTs will follow in a separate PR
> Refactoring. NetworkProvider.GetAccountBalance() - a single method for getting balances

- cmd/rosetta/config.go
- cmd/rosetta/config_test.go
- cmd/rosetta/main.go
- Fix loading of custom currencies. Use an empty list if the config file is not specified.
> Fix loading of custom currencies. Empty list if file not specified.

- server/services/constants.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- Handle native value transfers within `MultiESDTNFTTransfer`: `EGLD-000000`.
> Handle native value transfers within "MultiESDTNFTTransfer"

- server/services/constants.go
- server/services/transactionEvents.go
- Define some events (and constants), prepare their handling. The actual handling of these events comes in a future PR.
> Define some events (and constants), prepare their handling

- server/services/testdata/blocks_with_contract_calls.json
- server/services/testdata/blocks_with_contract_deployments.json
- server/services/transactionsFeaturesDetector.go
- server/services/transactionsFeaturesDetector_test.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- systemtests/check_with_mesh_cli.py
Handle:
- direct contract deployments bearing value, processed with signal error
- intra-shard contract calls bearing value, processed with signal error.
For these, only the fee operation is emitted.
A possibility for simplification (not yet confirmed): if `for all transactions having a child event of type signal error (direct child event, not of subsequent SCRs), we should only emit the fee operation` is a true statement, we can simplify many portions of the code. However, verifying this statement is postponed.
> Handle deployments and calls, with value, with signal error

- server/provider/scheduledMiniblocks.go
- server/services/networkProviderExtension.go
- server/services/transactionsFeaturesDetector.go
- server/services/transactionsFeaturesDetector_test.go
- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
- systemtests/check_with_mesh_cli.py
Handle & dismiss ineffective refunds (SCRs having `sender == receiver`, where the `IsRefund` marker is present).
See analysis on BigQuery:
https://console.cloud.google.com/bigquery?sq=667383445384:de7a5f3f172f4b50a9aaed353ef79839
> Handle & dismiss ineffective refunds

- server/services/transactionsTransformer.go
- server/services/transactionsTransformer_test.go
Fix regression of https://github.com/multiversx/mx-chain-rosetta/pull/97.
> Fix regression: different handling of transactions with signal error before vs. after Sirius

- server/provider/constants.go
- server/provider/networkProvider.go
- server/provider/scheduledMiniblocks.go
- server/provider/scheduledMiniblocks_test.go
- In each block N, accumulate all transactions that produced their effects in block N. Ignore all transactions found in block N, but whose effects were applied in previous blocks.
- Redesign logic on scheduled transactions around the function `gatherEffectiveTransactions`.
- Effective transactions are then added to "artificial" miniblocks.
> Rewrite logic on scheduled transactions: simplifyBlockWithScheduledTransactions()

- cmd/rosetta/cli.go
- cmd/rosetta/main.go
- cmd/rosetta/pprof.go
- server/services/accountService.go
- server/services/blockService.go
- server/services/constants.go
- server/services/transactionsTransformer.go
- systemtests/check_with_mesh_cli.py
- Enable `pprof` HTTP endpoints with CLI flag
- https://stackoverflow.com/a/71032595/1475331
- https://pkg.go.dev/net/http/pprof
- Measure get block, get account - display messages for a given duration threshold
> Enable pprof HTTP endpoints with CLI flag

- server/services/constants.go
- server/services/transactionEventsController.go
- server/services/transactionEventsController_test.go
- systemtests/check_with_mesh_cli.py
- version/constants.go
Original reconciliation failure:
```
Command Failed: unable to sync to 26038290: failed to sequence block range 26035294-26038290: unable to process block range 26035294-26038290: 
unable to process block 26035294: failed to handle the event of block 26035294 is added: unable to add block 26035294 (block hash: e447fbfbfe40e83a24c81f983aeb8271328d482058923979f26dfdd191c512ba) to storage: 
unable to update balance: account balance -24625648702188092 of currency {"symbol":"EGLD","decimals":18} for 
account {"address":"erd1qqqqqqqqqqqqqpgqkcllq2mgrnshhf543ese6gww3y2fjgs6u7zsmq34k6"} at block {"index":26035294,"hash":"e447fbfbfe40e83a24c81f983aeb8271328d482058923979f26dfdd191c512ba"} is invalid: negative balance
```
The `transfer value only` event with value `0.024625648702188092` was …
> Fix reconcilation failure: improve detection of (in)effective "transfer value only" events
